kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metro-telegram-bot-logs-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: local-storage
  resources:
   requests:
     storage: 100Mi
