apiVersion: v1
kind: Service
metadata:
 name: path-calculation-app-service
 namespace: metro-telegram-bot
spec:
 type: ClusterIP
 ports:
 - targetPort: 8001
   port: 8001
 selector:
   app: path-calculation-app

