apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: metro-telegram-bot
spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432
  selector:
    app: metrobot-postgres
