apiVersion: v1
kind: Service
metadata:
 name: redis-telegram-bot-service
 namespace: metro-telegram-bot
spec:
 type: ClusterIP
 ports:
 - targetPort: 6379
   port: 6379
 selector:
   app: redis-telegram-bot
